gText_Birch_Welcome::
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is AutumnSpark1226.\n"
	.string "(I look exactly like BIRCH)\p"
	.string "I am the person who created this hack.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is a POKéMON.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "As you are playing a hack,\n"
	.string "I assume you already played\l"
	.string "some POKéMON games.\p"
	.string "So let's get started!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "What are you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving\n"
	.string "to LITTLEROOT.\p"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Have fun!\p"
	.string "$"
